apiVersion: v1
kind: Pod
metadata:
  name: busybox-pvc
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo Hello from EBS > /data/hello.txt && sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: ebs-volume
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
  volumes:
  - name: ebs-volume
    persistentVolumeClaim:
      claimName: ebs-pvc
